### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_multipart#1]
In haxelib.json don't seem to be correct, it has tink_state in there?

**Comment by back2dos** [comment]
Apparently it's used here: https://github.com/haxetink/tink_multipart/blob/310d7e43343eb53bcdcb9fdf26fdbb0e82a24dd8/src/tink/multipart/parsers/BusboyParser.hx#L25

Seems slightly overkill, but then again I guess that one extra dependency shouldn't make much of a difference, no?

**Comment by benmerckx** [comment]
My bad. I didn't use the busyboy parser and just assumed this was a mistake :)
